services:
  #loki:
  #  image: grafana/loki:latest
  #  container_name: loki
  #  ports:
  #    - "3100:3100"
  #  volumes:
  #    - ./loki-config.yaml:/etc/loki/local-config.yaml

  gnmic:
    image: ghcr.io/openconfig/gnmic:latest
    container_name: gnmic
    volumes:
      - ./gnmic/config.yaml:/etc/gnmic/config.yaml
    ports:
      - 9273:9273
    command: ["subscribe", "--config", "/etc/gnmic/config.yaml"]
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      #- ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      #- ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      #- ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/json/dashboards.yaml
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - grafanadata:/var/lib/grafana

volumes:
  grafanadata:
  prometheusdata:
  #gnmic:
